#!/usr/bin/with-contenv bash

# ipfs config
if [ ! -d "/config/ipfs" ]; then
    ipfs init
    ipfs config --json API.HTTPHeaders.Access-Control-Allow-Origin '["*"]'
    ipfs config --json API.HTTPHeaders.Access-Control-Allow-Methods '["PUT", "POST"]'
    ipfs config --json Addresses.API '"/ip4/0.0.0.0/tcp/5001"'
    ipfs config --json Addresses.Gateway '"/ip4/0.0.0.0/tcp/8080"'
fi

# make our folders
mkdir -p \
    /config/{nginx/site-confs,log/nginx,keys} \
    /run \
    /var/lib/nginx/tmp/client_body \
    /var/tmp/nginx

# copy config files
[[ ! -f /config/nginx/nginx.conf ]] && \
    cp /defaults/nginx.conf /config/nginx/nginx.conf
[[ ! -f /config/nginx/site-confs/default ]] && \
    cp /defaults/default /config/nginx/site-confs/default

# permissions
chown -R abc:abc \
    /config \
    /var/lib/nginx \
    /var/tmp/nginx
chmod -R g+w \
    /config/nginx
chmod -R 644 /etc/logrotate.d
